# Generated by Django 6.0.2 on 2026-02-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_route', to='routes.airport')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='routes.airport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent', 'position'), name='unique_parent_position')],
            },
        ),
    ]
