# Generated by Django 6.0.2 on 2026-02-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='unique_parent_position',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='child',
            new_name='child_airport',
        ),
        migrations.AddField(
            model_name='route',
            name='parent_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_routes', to='routes.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='position',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('parent_airport', 'position'), name='unique_parent_side'),
        ),
        migrations.RemoveField(
            model_name='route',
            name='parent',
        ),
    ]
